name: Ubuntu (nps)

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Leave only desired OS in the field'
        required: true
        default: 'ubuntu-20.04'
        #default: 'windows-2016 | windows-2019 | ubuntu-16.04 | ubuntu-18.04 | ubuntu-20.04 | macos-10.15 | macos-11.0'
jobs:
  Instance:
    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Meet OS specific prerequisites
      run: |
        if('${{ runner.os }}' -eq 'Linux')
        {
          printf "# Preparing environment..."
            whoami > ssh_user
          printf " [DONE]\n\n"
          
          echo "# Change the SSH user password"
            echo "${{ inputs.SSH_PASS }}`n${{ inputs.SSH_PASS }}" | sudo passwd $(cat ssh_user)
        }
     
      shell: pwsh



    - name: Run Start Script
      run: source run.sh
